### POST REQUEST TO GET TOKEN
POST http://127.0.0.1:9000/auth HTTP/1.1
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}

### POST REQUEST FOR NEW USER
POST http://127.0.0.1:9000/auth/newuser HTTP/1.1
Content-Type: application/json

{
    "name": "admi1n1233",
    "password": "admin"
}